console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .UserName }} '
    foreground = 'blue'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>in</> {{ .Path }} '
    foreground = 'cyan'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = '<#ffffff>on</> {{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#ff94df'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' <#ff94df><b> </b></>'
      fetch_stash_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    #foreground = 'lightGreen'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']
